version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Prebuild, installing npm dependencies"
      - npm install
  build:
    commands:
      - echo "Starting the build step"
      - npm run build
      - cp -ra ./server/ ./dist/aws-codepipeline-build/
      - cp -ra ./bin/ ./dist/aws-codepipeline-build/
      - cp -ra ./aws/appspec.yml ./dist/aws-codepipeline-build/
      - echo "Finished"
artifacts:
  name: "BuildOutput"
  files:
    - '**/*'
  base-directory: 'dist/aws-codepipeline-build'